#!/usr/bin/env bash

guix pull
guix package -i stow vim
cd ./configs
for PACKAGE in *; do stow $PACKAGE -t $HOME; done
cd ..
guix pull # for new channels
cd ./configs-root/
for PACKAGE in *; do sudo stow $PACKAGE -t /; done
cd ..
sudo chown -R root ./configs-root/
sudo guix archive --authorize < /etc/signing-key.pub
sudo guix system reconfigure /etc/config.scm --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org https://substitutes.nonguix.org'
